version: "3.8"

services:
  api1: &api
    image: luanroger/rinha-api-2024q1:latest
    container_name: api1
    hostname: api1
    ports:
      - "5000:8080"
    environment:
      - POSTGRES_CONNECTION=Host=rinha-db;Port=5432;Database=postgres;Username=admin;Password=admin;
    depends_on:
      - db
    networks:
      - api-network
      - proxy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    ports:
      - "5001:8080"
      
  nginx:
    image: nginx:latest
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    networks:
      - proxy
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

  db:
    image: postgres:latest
    container_name: rinha-db
    hostname: rinha-db
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    networks:
      - api-network
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "250MB"

networks:
  api-network:
  proxy:
