CREATE TABLE IF NOT EXISTS public.Clientes (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saldo int NOT NULL,
    limite int NOT NULL
);

CREATE TABLE IF NOT EXISTS public.Transacoes (
    id int NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor int NOT NULL,
    tipo char NOT NULL,
    descricao varchar NOT NULL,
    realizadoEm timestamp NOT NULL,
    clienteId int REFERENCES Clientes(id)
);

INSERT INTO public.Clientes (saldo, limite) VALUES
	 (0, 100000),
	 (0, 80000),
	 (0, 1000000),
	 (0, 10000000),
	 (0, 500000);